name: Publish 1.8.9

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  MINECRAFT_VERSION: 1.8.9
  JAVA_VERSION: 8
  LOADER: forge
  VERSION: 0.0.1-alpha+1.8.9
  NAME: NotifHy 0.0.1-alpha+1.8.9
  FILE: /build/libs/*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Debug
        run: ls

      - name: Debug 2
        run: cd build

      - name: Debug 3
        run: ls

      - name: Debug 4
        run: cd libs

      - name: Debug 6
        run: ls

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          github-tag: "v${{ env.VERSION }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

          name: "${{ env.RELEASE_NAME }}"
          version: "${{ env.VERSION }}"

          loaders: "${{ env.LOADER }}"
          game-versions: "${{ env.MINECRAFT_VERSION }}"
          java: "${{ env.JAVA_VERSION }}"

          files: "${{ env.FILE }}"