name: Publish

on:
  workflow_dispatch:
    inputs:
      loader:
        description: "Mod Loader"
        required: true
        default: fabric
        type: choice
        options:
          - fabric
          - forge
      gradle_java_version:
        description: "Gradle Java Version"
        required: true
        default: "17"
        type: string
      minecraft_java_version:
        description: "Minecraft Java Version"
        required: true
        default: "17"
        type: string
      version_core:
        description: "Version Core"
        required: true
        type: string
      version_type:
        description: "Version Type"
        required: false
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: ${{ inputs.gradle_java_version }}

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Extract Branch Name
        id: branch
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Generate Version
        id: version
        run: |
          version="${{ inputs.version_core }}"
          
          if [[ "${{ inputs.version_type }}" != "" ]]; then
            version+="-${{ inputs.version_type }}"
          fi
          
          version+="+${{ steps.branch.outputs.branch }}"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Generate Name
        id: name
        run: |
          name="${{ inputs.version_core }}"
          version_type="${{ inputs.version_type }}"
          
          if [[ $version_type != "" ]]; then
            name+=" ${version_type^}"
          fi
          
          name+=" for ${{ steps.branch.outputs.branch }}"
          echo "name=$name" >> $GITHUB_OUTPUT

      - name: Build
        run: ./gradlew clean build

      - name: Write Version
        uses: christian-draeger/write-properties@1.1.0
        with:
          path: 'gradle.properties'
          property: |
            "mod_version"
          value: |
            "${{ steps.version.outputs.version }}"

      - name: Rename Build
        if: ${{ inputs.loader == 'forge' }}
        run: |
          mv build/libs/notifhy-${{ steps.version.outputs.version }}-all.jar build/libs/notifhy-${{ steps.version.outputs.version }}.jar

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          github-commitish: "${{ steps.branch.outputs.branch }}"
          github-tag: "${{ steps.version.outputs.version }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

          name: "${{ steps.name.outputs.name }}"
          version: "${{ steps.version.outputs.version }}"

          loaders: "${{ inputs.loader }}"
          game-versions: "${{ steps.branch.outputs.branch }}"
          java: "${{ inputs.minecraft_java_version }}"

          files: "build/libs/notifhy-${{ steps.version.outputs.version }}.jar"