name: Publish

on:
  workflow_dispatch:
    inputs:
      loader:
        description: "Mod loader"
        required: true
        type: choice
        options:
          - fabric
          - forge
      java_version:
        description: "Version of Java to built with"
        required: true
        type: string
      version_core:
        description: "See semver.org for details"
        required: true
        type: string
      version_type:
        description: "See semver.org for details"
        required: true
        type: string
env:
  LOADER: fabric
  JAVA_VERSION: 17
  VERSION_CORE: 0.0.1
  VERSION_TYPE: alpha

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != "Windows" }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Extract Branch Name
        id: branch
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Generate Version
        id: version
        run: |
          version="${{ env.VERSION_CORE }}"
          
          if [[ "${{ env.VERSION_TYPE }}" != "" ]]; then
            version+="-${{ env.VERSION_TYPE }}"
          fi
          
          version+="+${{ steps.branch.outputs.branch }}"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Generate Name
        id: name
        run: |
          name="${{ env.VERSION_CORE }}"
          version_type="${{ env.VERSION_TYPE }}"
          
          if [[ $version_type != "" ]]; then
            name+=" ${version_type^}"
          fi
          
          name+=" for ${{ steps.branch.outputs.branch }}"
          echo "name=$name" >> $GITHUB_OUTPUT

      - name: Rename Build
        if: ${{ env.LOADER }} === "forge"
        run: |
          mv build/libs/notifhy-${{ steps.version.outputs.version }}-all.jar build/libs/notifhy-${{ steps.version.outputs.version }}.jar

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          github-commitish: "${{ steps.branch.outputs.branch }}"
          github-tag: "${{ steps.version.outputs.version }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

          name: "${{ steps.name.outputs.name }}"
          version: "${{ steps.version.outputs.version }}"

          loaders: "${{ env.LOADER }}"
          game-versions: "${{ steps.branch.outputs.branch }}"
          java: "${{ env.JAVA_VERSION }}"

          files: "build/libs/notifhy-${{ steps.version.outputs.version }}.jar"